### ISSUE TITLE
Redirect to mink/dashboard "Page not found"

### ISSUE THREAD

**Issue by anne17** [spraakbanken/mink-frontend#63]
Sometimes when I log in I am being redirected to https://spraakbanken.gu.se/mink/dashboard and a "Page not found" message. I think this happens when the frontend times out, but somewhere in the login universe I am still logged in with my x-account.

**Comment by arildm** [comment]
Could this have happened only once? On Jan 31 (c6902f0), I renamed the `/dashboard` route to `/corpus`, and I cannot find any traces of the old path in the code now. So, could it be that your browser still remembered the redirect as `/dashboard` from before this change was deployed?

Has it happened again since this issue was created?
